language: python

dist: xenial

python:
  - "3.7"

cache:
  - pip

install:
  - pip install -r requirements-dev.txt
  - pip install codecov

script:
  - pytest --cov kformat --cov-branch

after_script:
  - codecov

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    branch: master
